velero:
{{- if and (hasKey .Requirements "velero") (hasKey .Requirements.velero "namespace") }}
  {{- if .Requirements.velero.namespace }}
  enabled: true
  {{- else }}
  enabled: false
  {{- end }}
{{- else }}
  enabled: false
{{- end }}
  rbac:
    create: true
  credentials:
    useSecret: true
    existingSecret: velero-secret
{{- if eq .Requirements.cluster.provider "gke" }}
  configuration:
    provider: gcp
    backupStorageLocation:
      name: gcp
      bucket: {{ .Requirements.storage.backup.url | removeScheme | quote }}
{{- else if or (eq .Requirements.cluster.provider "aws") (eq .Requirements.cluster.provider "eks") }}
  configuration:
    provider: aws
    backupStorageLocation:
      name: aws
      bucket: {{ .Requirements.storage.backup.url | removeScheme | quote }}
      config:
        region: {{ .Requirements.cluster.region | quote }}
    volumeSnapshotLocation:
      config:
        region: {{ .Requirements.cluster.region | quote }}
# Init containers to add to the Velero deployment's pod spec. At least one plugin provider image is required.
  initContainers:
    - name: velero-plugin-for-aws
      image: velero/velero-plugin-for-aws:v1.0.0
      imagePullPolicy: IfNotPresent
      volumeMounts:
        - mountPath: /target
          name: plugins
        
        
{{- else if eq .Requirements.cluster.provider "azure" }}
  configuration:
    provider: azure
    backupStorageLocation:
      name: azure
      bucket: {{ .Requirements.storage.backup.url | removeScheme | quote }}
      config:
        storageAccount: {{ .Requirements.velero.serviceAccount | quote }}
{{- else if eq .Requirements.cluster.provider "iks" }}
  snapshotsEnabled: false
  configuration:
    provider: aws
    backupStorageLocation:
      name: aws
      bucket: bucket-name
      config:
        region: {{ .Requirements.cluster.region | quote }}
        s3ForcePathStyle: "true"
        s3Url: {{ .Requirements.storage.backup.url | quote }}
{{- end }}

