dependencies:
- name: jxboot-resources
  repository: http://chartmuseum.jenkins-x.io
- alias: tekton
  name: tekton
  repository: http://chartmuseum.jenkins-x.io
- alias: prow
  condition: prow.enabled
  name: prow
  repository: http://chartmuseum.jenkins-x.io
- alias: lighthouse
  condition: lighthouse.enabled
  name: lighthouse
  repository: http://chartmuseum.jenkins-x.io
- alias: bucketrepo
  condition: bucketrepo.enabled
  name: bucketrepo
  repository: http://chartmuseum.jenkins-x.io
- name: jenkins-x-platform
  repository: http://chartmuseum.jenkins-x.io
- alias: prometheus-operator
  name: prometheus-operator
  repository: https://kubernetes-charts.storage.googleapis.com
  version: 8.5.0
- alias: istio-operator
  name: istio-operator
  repository: https://kubernetes-charts.banzaicloud.com
  version: 0.0.30
- alias: jaeger-operator
  name: jaeger-operator
  repository: https://jaegertracing.github.io/helm-charts
  version: 2.12.2
